language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t appstream-glib-fedora -f contrib/ci/Dockerfile-fedora .
  - docker build -t appstream-glib-debian-buster -f contrib/ci/Dockerfile-debian-buster .

script:
  - docker run -t -v `pwd`:/build appstream-glib-fedora ./contrib/ci/build_and_test.sh -Drpm=true -Ddep11=false
  - docker run -t -v `pwd`:/build appstream-glib-debian-buster ./contrib/ci/build_and_test.sh -Drpm=false -Ddep11=true
