language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t appstream-glib-fedora-29 -f contrib/ci/Dockerfile-fedora-29 .
  - docker build -t appstream-glib-debian-buster -f contrib/ci/Dockerfile-debian-buster .

script:
  - docker run -t -v `pwd`:/build appstream-glib-fedora-29 ./contrib/ci/build_and_test.sh -Drpm=true -Ddep11=false
  - docker run -t -v `pwd`:/build appstream-glib-debian-buster ./contrib/ci/build_and_test.sh -Drpm=false -Ddep11=true
